
--
-- Create user brms
--

DROP USER brms CASCADE;
CREATE USER brms IDENTIFIED BY brms;
GRANT CREATE SESSION TO brms;
GRANT CONNECT TO brms;
GRANT RESOURCE TO brms;


--------------------------------------------------------
--  DDL for Sequence VERSIONING_PM_SEQ_NAMES_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BRMS"."VERSIONING_PM_SEQ_NAMES_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FS_FSENTRY
--------------------------------------------------------

  CREATE TABLE "BRMS"."FS_FSENTRY" 
   (	"FSENTRY_PATH" VARCHAR2(2048 BYTE), 
	"FSENTRY_NAME" VARCHAR2(255 BYTE), 
	"FSENTRY_DATA" BLOB, 
	"FSENTRY_LASTMOD" NUMBER(38,0), 
	"FSENTRY_LENGTH" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FSENTRY_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table VERSIONING_FS_FSENTRY
--------------------------------------------------------

  CREATE TABLE "BRMS"."VERSIONING_FS_FSENTRY" 
   (	"FSENTRY_PATH" VARCHAR2(2048 BYTE), 
	"FSENTRY_NAME" VARCHAR2(255 BYTE), 
	"FSENTRY_DATA" BLOB, 
	"FSENTRY_LASTMOD" NUMBER(38,0), 
	"FSENTRY_LENGTH" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FSENTRY_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table VERSIONING_PM_BINVAL
--------------------------------------------------------

  CREATE TABLE "BRMS"."VERSIONING_PM_BINVAL" 
   (	"BINVAL_ID" VARCHAR2(64 BYTE), 
	"BINVAL_DATA" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BINVAL_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table VERSIONING_PM_BUNDLE
--------------------------------------------------------

  CREATE TABLE "BRMS"."VERSIONING_PM_BUNDLE" 
   (	"NODE_ID" RAW(16), 
	"BUNDLE_DATA" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BUNDLE_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table VERSIONING_PM_NAMES
--------------------------------------------------------

  CREATE TABLE "BRMS"."VERSIONING_PM_NAMES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VERSIONING_PM_REFS
--------------------------------------------------------

  CREATE TABLE "BRMS"."VERSIONING_PM_REFS" 
   (	"NODE_ID" RAW(16), 
	"REFS_DATA" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("REFS_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

--------------------------------------------------------
--  DDL for Index VERSIONING_PM_BUNDLE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRMS"."VERSIONING_PM_BUNDLE_IDX" ON "BRMS"."VERSIONING_PM_BUNDLE" ("NODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VERSIONING_PM_NAMES_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRMS"."VERSIONING_PM_NAMES_IDX" ON "BRMS"."VERSIONING_PM_NAMES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VERSIONING_PM_REFS_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRMS"."VERSIONING_PM_REFS_IDX" ON "BRMS"."VERSIONING_PM_REFS" ("NODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VERSIONING_FS_FSENTRY_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRMS"."VERSIONING_FS_FSENTRY_IDX" ON "BRMS"."VERSIONING_FS_FSENTRY" ("FSENTRY_PATH", "FSENTRY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VERSIONING_PM_BINVAL_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRMS"."VERSIONING_PM_BINVAL_IDX" ON "BRMS"."VERSIONING_PM_BINVAL" ("BINVAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FS_FSENTRY_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRMS"."FS_FSENTRY_IDX" ON "BRMS"."FS_FSENTRY" ("FSENTRY_PATH", "FSENTRY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FS_FSENTRY
--------------------------------------------------------

  ALTER TABLE "BRMS"."FS_FSENTRY" MODIFY ("FSENTRY_LASTMOD" NOT NULL ENABLE);
  ALTER TABLE "BRMS"."FS_FSENTRY" MODIFY ("FSENTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BRMS"."FS_FSENTRY" MODIFY ("FSENTRY_PATH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VERSIONING_FS_FSENTRY
--------------------------------------------------------

  ALTER TABLE "BRMS"."VERSIONING_FS_FSENTRY" MODIFY ("FSENTRY_LASTMOD" NOT NULL ENABLE);
  ALTER TABLE "BRMS"."VERSIONING_FS_FSENTRY" MODIFY ("FSENTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BRMS"."VERSIONING_FS_FSENTRY" MODIFY ("FSENTRY_PATH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VERSIONING_PM_BINVAL
--------------------------------------------------------

  ALTER TABLE "BRMS"."VERSIONING_PM_BINVAL" MODIFY ("BINVAL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VERSIONING_PM_NAMES
--------------------------------------------------------

  ALTER TABLE "BRMS"."VERSIONING_PM_NAMES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BRMS"."VERSIONING_PM_NAMES" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VERSIONING_PM_REFS
--------------------------------------------------------

  ALTER TABLE "BRMS"."VERSIONING_PM_REFS" MODIFY ("REFS_DATA" NOT NULL ENABLE);
  ALTER TABLE "BRMS"."VERSIONING_PM_REFS" MODIFY ("NODE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VERSIONING_PM_BUNDLE
--------------------------------------------------------

  ALTER TABLE "BRMS"."VERSIONING_PM_BUNDLE" MODIFY ("NODE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger VERSIONING_PM_T1
--------------------------------------------------------


  CREATE OR REPLACE TRIGGER "BRMS"."VERSIONING_PM_T1" before insert on "BRMS"."VERSIONING_PM_NAMES" for each row begin select VERSIONING_PM_seq_names_id.nextval into :new.id from dual; end;
/
ALTER TRIGGER "BRMS"."VERSIONING_PM_T1" ENABLE;
