
--
-- Create user jbpm
--

DROP USER jbpm CASCADE;
CREATE USER jbpm IDENTIFIED BY jbpm;
GRANT CREATE SESSION TO jbpm;
GRANT CONNECT TO jbpm;
GRANT RESOURCE TO jbpm;

GRANT SELECT ON sys.dba_pending_transactions TO jbpm;
GRANT SELECT ON sys.pending_trans$ TO jbpm;
GRANT SELECT ON sys.dba_2pc_pending TO jbpm;
GRANT EXECUTE ON sys.dbms_xa TO jbpm;

--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "JBPM"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SESSIONINFO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JBPM"."SESSIONINFO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WORKITEMINFO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JBPM"."WORKITEMINFO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "JBPM"."ATTACHMENT" 
   (	"ID" NUMBER(19,0), 
	"ACCESSTYPE" NUMBER(10,0), 
	"ATTACHEDAT" TIMESTAMP (6), 
	"ATTACHMENTCONTENTID" NUMBER(19,0), 
	"CONTENTTYPE" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"ATTACHMENT_SIZE" NUMBER(10,0), 
	"ATTACHEDBY_ID" VARCHAR2(255 CHAR), 
	"TASKDATA_ATTACHMENTS_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOLEANEXPRESSION
--------------------------------------------------------

  CREATE TABLE "JBPM"."BOOLEANEXPRESSION" 
   (	"ID" NUMBER(19,0), 
	"EXPRESSION" CLOB, 
	"TYPE" VARCHAR2(255 CHAR), 
	"ESCALATION_CONSTRAINTS_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("EXPRESSION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CONTENT
--------------------------------------------------------

  CREATE TABLE "JBPM"."CONTENT" 
   (	"ID" NUMBER(19,0), 
	"CONTENT" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DEADLINE
--------------------------------------------------------

  CREATE TABLE "JBPM"."DEADLINE" 
   (	"ID" NUMBER(19,0), 
	"DEADLINE_DATE" TIMESTAMP (6), 
	"ESCALATED" NUMBER(5,0), 
	"DEADLINES_STARTDEADLINE_ID" NUMBER(19,0), 
	"DEADLINES_ENDDEADLINE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DELEGATION_DELEGATES
--------------------------------------------------------

  CREATE TABLE "JBPM"."DELEGATION_DELEGATES" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMAIL_HEADER
--------------------------------------------------------

  CREATE TABLE "JBPM"."EMAIL_HEADER" 
   (	"ID" NUMBER(19,0), 
	"BODY" CLOB, 
	"FROMADDRESS" VARCHAR2(255 CHAR), 
	"LANGUAGE" VARCHAR2(255 CHAR), 
	"REPLYTOADDRESS" VARCHAR2(255 CHAR), 
	"SUBJECT" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BODY") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ESCALATION
--------------------------------------------------------

  CREATE TABLE "JBPM"."ESCALATION" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"DEADLINE_ESCALATION_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTTYPES
--------------------------------------------------------

  CREATE TABLE "JBPM"."EVENTTYPES" 
   (	"INSTANCEID" NUMBER(19,0), 
	"EVENTTYPES" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I18NTEXT
--------------------------------------------------------

  CREATE TABLE "JBPM"."I18NTEXT" 
   (	"ID" NUMBER(19,0), 
	"LANGUAGE" VARCHAR2(255 CHAR), 
	"SHORTTEXT" VARCHAR2(255 CHAR), 
	"TEXT" CLOB, 
	"TASK_SUBJECTS_ID" NUMBER(19,0), 
	"TASK_NAMES_ID" NUMBER(19,0), 
	"TASK_DESCRIPTIONS_ID" NUMBER(19,0), 
	"REASSIGNMENT_DOCUMENTATION_ID" NUMBER(19,0), 
	"NOTIFICATION_SUBJECTS_ID" NUMBER(19,0), 
	"NOTIFICATION_NAMES_ID" NUMBER(19,0), 
	"NOTIFICATION_DOCUMENTATION_ID" NUMBER(19,0), 
	"NOTIFICATION_DESCRIPTIONS_ID" NUMBER(19,0), 
	"DEADLINE_DOCUMENTATION_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table NODEINSTANCELOG
--------------------------------------------------------

  CREATE TABLE "JBPM"."NODEINSTANCELOG" 
   (	"ID" NUMBER(19,0), 
	"LOG_DATE" TIMESTAMP (6), 
	"NODEID" VARCHAR2(255 CHAR), 
	"NODEINSTANCEID" VARCHAR2(255 CHAR), 
	"NODENAME" VARCHAR2(255 CHAR), 
	"PROCESSID" VARCHAR2(255 CHAR), 
	"PROCESSINSTANCEID" NUMBER(19,0), 
	"TYPE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "JBPM"."NOTIFICATION" 
   (	"DTYPE" VARCHAR2(31 CHAR), 
	"ID" NUMBER(19,0), 
	"PRIORITY" NUMBER(10,0), 
	"ESCALATION_NOTIFICATIONS_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION_BAS
--------------------------------------------------------

  CREATE TABLE "JBPM"."NOTIFICATION_BAS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION_EMAIL_HEADER
--------------------------------------------------------

  CREATE TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" 
   (	"NOTIFICATION_ID" NUMBER(19,0), 
	"EMAILHEADERS_ID" NUMBER(19,0), 
	"MAPKEY" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION_RECIPIENTS
--------------------------------------------------------

  CREATE TABLE "JBPM"."NOTIFICATION_RECIPIENTS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORGANIZATIONALENTITY
--------------------------------------------------------

  CREATE TABLE "JBPM"."ORGANIZATIONALENTITY" 
   (	"DTYPE" VARCHAR2(31 CHAR), 
	"ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLEASSIGNMENTS_BAS
--------------------------------------------------------

  CREATE TABLE "JBPM"."PEOPLEASSIGNMENTS_BAS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLEASSIGNMENTS_EXCLOWNERS
--------------------------------------------------------

  CREATE TABLE "JBPM"."PEOPLEASSIGNMENTS_EXCLOWNERS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLEASSIGNMENTS_POTOWNERS
--------------------------------------------------------

  CREATE TABLE "JBPM"."PEOPLEASSIGNMENTS_POTOWNERS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLEASSIGNMENTS_RECIPIENTS
--------------------------------------------------------

  CREATE TABLE "JBPM"."PEOPLEASSIGNMENTS_RECIPIENTS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLEASSIGNMENTS_STAKEHOLDERS
--------------------------------------------------------

  CREATE TABLE "JBPM"."PEOPLEASSIGNMENTS_STAKEHOLDERS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROCESSINSTANCEINFO
--------------------------------------------------------

  CREATE TABLE "JBPM"."PROCESSINSTANCEINFO" 
   (	"INSTANCEID" NUMBER(19,0), 
	"ID" NUMBER(19,0), 
	"LASTMODIFICATIONDATE" TIMESTAMP (6), 
	"LASTREADDATE" TIMESTAMP (6), 
	"PROCESSID" VARCHAR2(255 CHAR), 
	"PROCESSINSTANCEBYTEARRAY" BLOB, 
	"STARTDATE" TIMESTAMP (6), 
	"STATE" NUMBER(10,0), 
	"OPTLOCK" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PROCESSINSTANCEBYTEARRAY") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PROCESSINSTANCELOG
--------------------------------------------------------

  CREATE TABLE "JBPM"."PROCESSINSTANCELOG" 
   (	"ID" NUMBER(19,0), 
	"END_DATE" TIMESTAMP (6), 
	"PROCESSID" VARCHAR2(255 CHAR), 
	"PROCESSINSTANCEID" NUMBER(19,0), 
	"START_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REASSIGNMENT
--------------------------------------------------------

  CREATE TABLE "JBPM"."REASSIGNMENT" 
   (	"ID" NUMBER(19,0), 
	"ESCALATION_REASSIGNMENTS_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REASSIGNMENT_POTENTIALOWNERS
--------------------------------------------------------

  CREATE TABLE "JBPM"."REASSIGNMENT_POTENTIALOWNERS" 
   (	"TASK_ID" NUMBER(19,0), 
	"ENTITY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SESSIONINFO
--------------------------------------------------------

  CREATE TABLE "JBPM"."SESSIONINFO" 
   (	"ID" NUMBER(10,0), 
	"LASTMODIFICATIONDATE" TIMESTAMP (6), 
	"RULESBYTEARRAY" BLOB, 
	"STARTDATE" TIMESTAMP (6), 
	"OPTLOCK" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("RULESBYTEARRAY") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUBTASKSSTRATEGY
--------------------------------------------------------

  CREATE TABLE "JBPM"."SUBTASKSSTRATEGY" 
   (	"DTYPE" VARCHAR2(100 CHAR), 
	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"TASK_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "JBPM"."TASK" 
   (	"ID" NUMBER(19,0), 
	"ARCHIVED" NUMBER(5,0), 
	"ALLOWEDTODELEGATE" VARCHAR2(255 CHAR), 
	"PRIORITY" NUMBER(10,0), 
	"ACTIVATIONTIME" TIMESTAMP (6), 
	"COMPLETEDON" TIMESTAMP (6), 
	"CREATEDON" TIMESTAMP (6), 
	"DOCUMENTACCESSTYPE" NUMBER(10,0), 
	"DOCUMENTCONTENTID" NUMBER(19,0), 
	"DOCUMENTTYPE" VARCHAR2(255 CHAR), 
	"EXPIRATIONTIME" TIMESTAMP (6), 
	"FAULTACCESSTYPE" NUMBER(10,0), 
	"FAULTCONTENTID" NUMBER(19,0), 
	"FAULTNAME" VARCHAR2(255 CHAR), 
	"FAULTTYPE" VARCHAR2(255 CHAR), 
	"OUTPUTACCESSTYPE" NUMBER(10,0), 
	"OUTPUTCONTENTID" NUMBER(19,0), 
	"OUTPUTTYPE" VARCHAR2(255 CHAR), 
	"PARENTID" NUMBER(19,0), 
	"PREVIOUSSTATUS" NUMBER(10,0), 
	"PROCESSID" VARCHAR2(255 CHAR), 
	"PROCESSINSTANCEID" NUMBER(19,0), 
	"PROCESSSESSIONID" NUMBER(10,0), 
	"SKIPABLE" NUMBER(1,0), 
	"STATUS" VARCHAR2(255 CHAR), 
	"WORKITEMID" NUMBER(19,0), 
	"OPTLOCK" NUMBER(10,0), 
	"TASKINITIATOR_ID" VARCHAR2(255 CHAR), 
	"ACTUALOWNER_ID" VARCHAR2(255 CHAR), 
	"CREATEDBY_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TASK_COMMENT
--------------------------------------------------------

  CREATE TABLE "JBPM"."TASK_COMMENT" 
   (	"ID" NUMBER(19,0), 
	"ADDEDAT" TIMESTAMP (6), 
	"TEXT" CLOB, 
	"ADDEDBY_ID" VARCHAR2(255 CHAR), 
	"TASKDATA_COMMENTS_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table VARIABLEINSTANCELOG
--------------------------------------------------------

  CREATE TABLE "JBPM"."VARIABLEINSTANCELOG" 
   (	"ID" NUMBER(19,0), 
	"LOG_DATE" TIMESTAMP (6), 
	"PROCESSID" VARCHAR2(255 CHAR), 
	"PROCESSINSTANCEID" NUMBER(19,0), 
	"VALUE" VARCHAR2(255 CHAR), 
	"VARIABLEID" VARCHAR2(255 CHAR), 
	"VARIABLEINSTANCEID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WORKITEMINFO
--------------------------------------------------------

  CREATE TABLE "JBPM"."WORKITEMINFO" 
   (	"WORKITEMID" NUMBER(19,0), 
	"CREATIONDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(255 CHAR), 
	"PROCESSINSTANCEID" NUMBER(19,0), 
	"STATE" NUMBER(19,0), 
	"OPTLOCK" NUMBER(10,0), 
	"WORKITEMBYTEARRAY" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("WORKITEMBYTEARRAY") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

--------------------------------------------------------
--  DDL for Index UK_PTAKA5KOST68H7L3WFLV7W6Y8
--------------------------------------------------------

  CREATE UNIQUE INDEX "JBPM"."UK_PTAKA5KOST68H7L3WFLV7W6Y8" ON "JBPM"."NOTIFICATION_EMAIL_HEADER" ("EMAILHEADERS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PEOPLEASSIGNMENTS_EXCLOWNERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_EXCLOWNERS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_EXCLOWNERS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REASSIGNMENT_POTENTIALOWNERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."REASSIGNMENT_POTENTIALOWNERS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."REASSIGNMENT_POTENTIALOWNERS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANIZATIONALENTITY
--------------------------------------------------------

  ALTER TABLE "JBPM"."ORGANIZATIONALENTITY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."ORGANIZATIONALENTITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."ORGANIZATIONALENTITY" MODIFY ("DTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROCESSINSTANCELOG
--------------------------------------------------------

  ALTER TABLE "JBPM"."PROCESSINSTANCELOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."PROCESSINSTANCELOG" MODIFY ("PROCESSINSTANCEID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."PROCESSINSTANCELOG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMAIL_HEADER
--------------------------------------------------------

  ALTER TABLE "JBPM"."EMAIL_HEADER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."EMAIL_HEADER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "JBPM"."TASK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."TASK" MODIFY ("WORKITEMID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("SKIPABLE" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("PROCESSSESSIONID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("PROCESSINSTANCEID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("PARENTID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("OUTPUTCONTENTID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("FAULTCONTENTID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("DOCUMENTCONTENTID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."TASK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION_BAS
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION_BAS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NOTIFICATION_BAS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEOPLEASSIGNMENTS_BAS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_BAS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_BAS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBTASKSSTRATEGY
--------------------------------------------------------

  ALTER TABLE "JBPM"."SUBTASKSSTRATEGY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."SUBTASKSSTRATEGY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."SUBTASKSSTRATEGY" MODIFY ("DTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEOPLEASSIGNMENTS_STAKEHOLDERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_STAKEHOLDERS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_STAKEHOLDERS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION_EMAIL_HEADER
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" ADD CONSTRAINT "UK_PTAKA5KOST68H7L3WFLV7W6Y8" UNIQUE ("EMAILHEADERS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" ADD PRIMARY KEY ("NOTIFICATION_ID", "MAPKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" MODIFY ("MAPKEY" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" MODIFY ("EMAILHEADERS_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" MODIFY ("NOTIFICATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEOPLEASSIGNMENTS_POTOWNERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_POTOWNERS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_POTOWNERS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOLEANEXPRESSION
--------------------------------------------------------

  ALTER TABLE "JBPM"."BOOLEANEXPRESSION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."BOOLEANEXPRESSION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SESSIONINFO
--------------------------------------------------------

  ALTER TABLE "JBPM"."SESSIONINFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."SESSIONINFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORKITEMINFO
--------------------------------------------------------

  ALTER TABLE "JBPM"."WORKITEMINFO" ADD PRIMARY KEY ("WORKITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."WORKITEMINFO" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."WORKITEMINFO" MODIFY ("PROCESSINSTANCEID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."WORKITEMINFO" MODIFY ("WORKITEMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEADLINE
--------------------------------------------------------

  ALTER TABLE "JBPM"."DEADLINE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."DEADLINE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DELEGATION_DELEGATES
--------------------------------------------------------

  ALTER TABLE "JBPM"."DELEGATION_DELEGATES" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."DELEGATION_DELEGATES" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "JBPM"."ATTACHMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."ATTACHMENT" MODIFY ("ATTACHMENTCONTENTID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."ATTACHMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTENT
--------------------------------------------------------

  ALTER TABLE "JBPM"."CONTENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."CONTENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TASK_COMMENT
--------------------------------------------------------

  ALTER TABLE "JBPM"."TASK_COMMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."TASK_COMMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table I18NTEXT
--------------------------------------------------------

  ALTER TABLE "JBPM"."I18NTEXT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "JBPM"."REASSIGNMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."REASSIGNMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION_RECIPIENTS
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION_RECIPIENTS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NOTIFICATION_RECIPIENTS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESCALATION
--------------------------------------------------------

  ALTER TABLE "JBPM"."ESCALATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."ESCALATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VARIABLEINSTANCELOG
--------------------------------------------------------

  ALTER TABLE "JBPM"."VARIABLEINSTANCELOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."VARIABLEINSTANCELOG" MODIFY ("PROCESSINSTANCEID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."VARIABLEINSTANCELOG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTTYPES
--------------------------------------------------------

  ALTER TABLE "JBPM"."EVENTTYPES" MODIFY ("INSTANCEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEOPLEASSIGNMENTS_RECIPIENTS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_RECIPIENTS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_RECIPIENTS" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."NOTIFICATION" MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NOTIFICATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NOTIFICATION" MODIFY ("DTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROCESSINSTANCEINFO
--------------------------------------------------------

  ALTER TABLE "JBPM"."PROCESSINSTANCEINFO" ADD PRIMARY KEY ("INSTANCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."PROCESSINSTANCEINFO" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."PROCESSINSTANCEINFO" MODIFY ("INSTANCEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NODEINSTANCELOG
--------------------------------------------------------

  ALTER TABLE "JBPM"."NODEINSTANCELOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBPM"."NODEINSTANCELOG" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NODEINSTANCELOG" MODIFY ("PROCESSINSTANCEID" NOT NULL ENABLE);
  ALTER TABLE "JBPM"."NODEINSTANCELOG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "JBPM"."ATTACHMENT" ADD CONSTRAINT "FK_7NDPFA311I50BQ7HY18Q05VA3" FOREIGN KEY ("ATTACHEDBY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
  ALTER TABLE "JBPM"."ATTACHMENT" ADD CONSTRAINT "FK_HQUPX569KRP0F0SGU9KH87513" FOREIGN KEY ("TASKDATA_ATTACHMENTS_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOLEANEXPRESSION
--------------------------------------------------------

  ALTER TABLE "JBPM"."BOOLEANEXPRESSION" ADD CONSTRAINT "FK_394NF2QOC0K9OK6OMGD6JTPSO" FOREIGN KEY ("ESCALATION_CONSTRAINTS_ID")
	  REFERENCES "JBPM"."ESCALATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEADLINE
--------------------------------------------------------

  ALTER TABLE "JBPM"."DEADLINE" ADD CONSTRAINT "FK_68W742SGE00VCO2CQ3JHBVMGX" FOREIGN KEY ("DEADLINES_STARTDEADLINE_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."DEADLINE" ADD CONSTRAINT "FK_EUOOHOELBQVV94D8A8RCG8S5N" FOREIGN KEY ("DEADLINES_ENDDEADLINE_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DELEGATION_DELEGATES
--------------------------------------------------------

  ALTER TABLE "JBPM"."DELEGATION_DELEGATES" ADD CONSTRAINT "FK_FAJQ6KOSSBSQWR3OPKRCTXEI3" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."DELEGATION_DELEGATES" ADD CONSTRAINT "FK_GN7ULA51SK55WJ1O1M57GUQXB" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESCALATION
--------------------------------------------------------

  ALTER TABLE "JBPM"."ESCALATION" ADD CONSTRAINT "FK_AY2GD4FVL9YAAPVIYXUDWUVFG" FOREIGN KEY ("DEADLINE_ESCALATION_ID")
	  REFERENCES "JBPM"."DEADLINE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTTYPES
--------------------------------------------------------

  ALTER TABLE "JBPM"."EVENTTYPES" ADD CONSTRAINT "FK_NRECJ4617IWXLC65IJ6M7LSL1" FOREIGN KEY ("INSTANCEID")
	  REFERENCES "JBPM"."PROCESSINSTANCEINFO" ("INSTANCEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I18NTEXT
--------------------------------------------------------

  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_21QVIFARXSVUXEAW5SXWH473W" FOREIGN KEY ("DEADLINE_DOCUMENTATION_ID")
	  REFERENCES "JBPM"."DEADLINE" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_4EYFP69UCRRON2HR7QX4NP2FP" FOREIGN KEY ("TASK_DESCRIPTIONS_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_BW8VMPEKEJXT1EI2GE26GDSRY" FOREIGN KEY ("NOTIFICATION_DESCRIPTIONS_ID")
	  REFERENCES "JBPM"."NOTIFICATION" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_FD9UK6HEMV2DX1OJOVO7MS3VP" FOREIGN KEY ("TASK_NAMES_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_G1TRXRI8W64ENUDW2T1QAHHK5" FOREIGN KEY ("NOTIFICATION_NAMES_ID")
	  REFERENCES "JBPM"."NOTIFICATION" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_K16JPGRH67TI9UEDF6KONSU1P" FOREIGN KEY ("TASK_SUBJECTS_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_O84RKH69R47TI8UV4EYJ7BMO2" FOREIGN KEY ("NOTIFICATION_SUBJECTS_ID")
	  REFERENCES "JBPM"."NOTIFICATION" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_PQARJVVNWFJPEYB87YD7M0BFI" FOREIGN KEY ("REASSIGNMENT_DOCUMENTATION_ID")
	  REFERENCES "JBPM"."REASSIGNMENT" ("ID") ENABLE;
  ALTER TABLE "JBPM"."I18NTEXT" ADD CONSTRAINT "FK_QOCE92C70ADEM3CCB3I7LEC8X" FOREIGN KEY ("NOTIFICATION_DOCUMENTATION_ID")
	  REFERENCES "JBPM"."NOTIFICATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION" ADD CONSTRAINT "FK_BDBEML3768GO5IM41CGFPYSO9" FOREIGN KEY ("ESCALATION_NOTIFICATIONS_ID")
	  REFERENCES "JBPM"."ESCALATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION_BAS
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION_BAS" ADD CONSTRAINT "FK_FC0UUY76T2BVXAXQYSOO8XTS7" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."NOTIFICATION" ("ID") ENABLE;
  ALTER TABLE "JBPM"."NOTIFICATION_BAS" ADD CONSTRAINT "FK_MFBSNBRHTH4RJHQC2UD338S4I" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION_EMAIL_HEADER
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" ADD CONSTRAINT "FK_ETH4NVXN21FK1VNJU85VKJRAI" FOREIGN KEY ("NOTIFICATION_ID")
	  REFERENCES "JBPM"."NOTIFICATION" ("ID") ENABLE;
  ALTER TABLE "JBPM"."NOTIFICATION_EMAIL_HEADER" ADD CONSTRAINT "FK_PTAKA5KOST68H7L3WFLV7W6Y8" FOREIGN KEY ("EMAILHEADERS_ID")
	  REFERENCES "JBPM"."EMAIL_HEADER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION_RECIPIENTS
--------------------------------------------------------

  ALTER TABLE "JBPM"."NOTIFICATION_RECIPIENTS" ADD CONSTRAINT "FK_3L244PJ8SH78VTN9IMAYMRG47" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."NOTIFICATION" ("ID") ENABLE;
  ALTER TABLE "JBPM"."NOTIFICATION_RECIPIENTS" ADD CONSTRAINT "FK_BLF9JSRUMTRTHDAQNPWXT25EU" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEOPLEASSIGNMENTS_BAS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_BAS" ADD CONSTRAINT "FK_OMJG5QH7UV8E9BOLBAQ7HV6OH" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_BAS" ADD CONSTRAINT "FK_T38XBKRQ6CPPIFNXEQUHVJSL2" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEOPLEASSIGNMENTS_EXCLOWNERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_EXCLOWNERS" ADD CONSTRAINT "FK_B8OWUXFRDNG050UGPK0PDOWA7" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_EXCLOWNERS" ADD CONSTRAINT "FK_PTH28A73RJ6BXTLFC69KMQO0A" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEOPLEASSIGNMENTS_POTOWNERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_POTOWNERS" ADD CONSTRAINT "FK_4DV2OJI7PR35RU0W45TRIX02X" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_POTOWNERS" ADD CONSTRAINT "FK_TEE3FTIR7XS6EO3FDVI3XW026" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEOPLEASSIGNMENTS_RECIPIENTS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_RECIPIENTS" ADD CONSTRAINT "FK_4G7Y3WX6GNOKF6VYCGPXS83D6" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_RECIPIENTS" ADD CONSTRAINT "FK_ENHK831FGHF6AKJILFN58OKL4" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEOPLEASSIGNMENTS_STAKEHOLDERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_STAKEHOLDERS" ADD CONSTRAINT "FK_4BH3AY74X6QL9USUNUBTTFDF1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."PEOPLEASSIGNMENTS_STAKEHOLDERS" ADD CONSTRAINT "FK_MET63INAEP6CQ4OFB3NNXI4TM" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "JBPM"."REASSIGNMENT" ADD CONSTRAINT "FK_PNPEUE9HS6KX2EP0SP16B6KFD" FOREIGN KEY ("ESCALATION_REASSIGNMENTS_ID")
	  REFERENCES "JBPM"."ESCALATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REASSIGNMENT_POTENTIALOWNERS
--------------------------------------------------------

  ALTER TABLE "JBPM"."REASSIGNMENT_POTENTIALOWNERS" ADD CONSTRAINT "FK_8FRL6LA7TGPARLNUKHP8XMODY" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
  ALTER TABLE "JBPM"."REASSIGNMENT_POTENTIALOWNERS" ADD CONSTRAINT "FK_QBEGA5NCU6B9YIGWLW55AEIJN" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."REASSIGNMENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBTASKSSTRATEGY
--------------------------------------------------------

  ALTER TABLE "JBPM"."SUBTASKSSTRATEGY" ADD CONSTRAINT "FK_IRVM6FQWH8WEBJ0JSFIIFQVQ1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "JBPM"."TASK" ADD CONSTRAINT "FK_DPK0F9UCM14C78BSXTHH7H8YH" FOREIGN KEY ("TASKINITIATOR_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
  ALTER TABLE "JBPM"."TASK" ADD CONSTRAINT "FK_K02OG0U71OBF1UXGCDJX9RCJC" FOREIGN KEY ("CREATEDBY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
  ALTER TABLE "JBPM"."TASK" ADD CONSTRAINT "FK_NH9NNT47F3L61QJLYEDQT05RF" FOREIGN KEY ("ACTUALOWNER_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TASK_COMMENT
--------------------------------------------------------

  ALTER TABLE "JBPM"."TASK_COMMENT" ADD CONSTRAINT "FK_1WS9JDMHTEY6MXU7JB0R0UFVS" FOREIGN KEY ("TASKDATA_COMMENTS_ID")
	  REFERENCES "JBPM"."TASK" ("ID") ENABLE;
  ALTER TABLE "JBPM"."TASK_COMMENT" ADD CONSTRAINT "FK_AAX378YJNSMW9KB9VSU994JJV" FOREIGN KEY ("ADDEDBY_ID")
	  REFERENCES "JBPM"."ORGANIZATIONALENTITY" ("ID") ENABLE;
